<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="9" total="11" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1305" started-at="2018-09-14T12:50:11Z" finished-at="2018-09-14T12:50:12Z">
    <groups>
      <group name="Working Tests">
        <method signature="Test_ABTesting.AB_Testing()[pri:0, instance:TestScript.Test_ABTesting@29f7cefd]" name="AB_Testing" class="TestScript.Test_ABTesting"/>
        <method signature="Test_BasicAuth.Basic_Auth()[pri:0, instance:TestScript.Test_BasicAuth@9816741]" name="Basic_Auth" class="TestScript.Test_BasicAuth"/>
      </group> <!-- Working Tests -->
    </groups>
    <test name="Test" duration-ms="1305" started-at="2018-09-14T12:50:11Z" finished-at="2018-09-14T12:50:12Z">
      <class name="TestScript.Test_BasicAuth">
        <test-method status="FAIL" signature="Basic_Auth()[pri:0, instance:TestScript.Test_BasicAuth@9816741]" name="Basic_Auth" duration-ms="2" started-at="2018-09-14T12:50:12Z" finished-at="2018-09-14T12:50:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at TestScript.Test_BasicAuth.Basic_Auth(Test_BasicAuth.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Basic_Auth -->
      </class> <!-- TestScript.Test_BasicAuth -->
      <class name="TestScript.Test_ABTesting">
        <test-method status="PASS" signature="AB_Testing()[pri:0, instance:TestScript.Test_ABTesting@29f7cefd]" name="AB_Testing" duration-ms="1161" started-at="2018-09-14T12:50:11Z" finished-at="2018-09-14T12:50:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AB_Testing -->
      </class> <!-- TestScript.Test_ABTesting -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
